name: Feature request（新機能リクエスト）
description: Suggest an idea for this project（このプロジェクトへのアイデアを提案する）
title: "[Feature Request]: "
labels: ["enhancement"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this ?（これに関する既知の問題はありますか？）
      description: Please search to see if an issue already exists for the feature you want, and that it's not implemented in a recent commit.（ご希望の機能に関するissueがすでに存在しないか、また最近のコミットで実装されていないか、検索してご確認ください。）
      options:
        - label: I have searched the existing issues and checked the recent builds/commits.（既存のissuesを検索し、最近のコミットを確認しました。）
          required: true
  - type: markdown
    attributes:
      value: |
        *Please fill this form with as much information as possible, provide screenshots and/or illustrations of the feature if possible.*
        *（このフォームにはできるだけ多くの情報を記入してください。また、可能であれば、その機能のスクリーンショットや図解を添付してください。）*
  - type: textarea
    id: feature
    attributes:
      label: What would your feature do ?（その機能はどのような働きをするのでしょうか？）
      description: Tell us about your feature in a very clear and simple way, and what problem it would solve.（その機能について、できるだけわかりやすく簡潔に説明してください。また、それがどのような問題を解決するのかについても教えてください。）
    validations:
      required: true
  - type: textarea
    id: workflow
    attributes:
      label: Proposed workflow（提案されるワークフロー）
      description: Please provide us with step by step information on how you'd like the feature to be accessed and used.（その機能へのアクセス方法や使用方法について、手順ごとに詳しくご説明ください。）
      value: |
        1. Go to .... 
        2. Press ....
        3. ...
  - type: textarea
    id: misc
    attributes:
      label: Additional information（補足情報）
      description: Add any other context or screenshots about the feature request here.（この機能リクエストに関するその他の背景情報やスクリーンショットがあれば、こちらに追加してください。）
